name: dev-ci

on:
    workflow_dispatch:
    push:
        branches: [dev]
    pull_request:
        branches: [dev]

jobs:
    build:
        runs-on: ubuntu-latest
        environment: dev-ci
        steps:
            - uses: actions/checkout@v2

            - name: use node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 14.x
                  cache: yarn

            - name: install dependencies
              run: yarn install --frozen-lockfile

              env:
                  SKIP_PREFLIGHT_CHECK: true
